name: '${project.name}'
version: '${project.version}'
main: pl.techbrat.spigot.globalaccount.GlobalAccountTB
api-version: 1.13
authors: [TechBart]
description: '${project.description}'
website: '${project.url}'
softdepend: [PlaceholderAPI]
commands:
  globalaccount:
    aliases: [ga, gaccount, globacct]
    permission: globaccttb.admin.command